spring.application.name=qlms-request-service
server.port=8083

spring.datasource.url=jdbc:postgresql://qlmsdb.postgres.database.azure.com:5432/qlms_request?sslmode=require
spring.datasource.username=qlmsadmin
spring.datasource.password=Qlms@123456
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

eureka.client.service-url.defaultZone=http://qlms-eureka:8761/eureka/
eureka.instance.prefer-ip-address=true
